import type { PropertyTabData } from "./types";
import { urgencyLabel } from "./types";

export const DEMO_PROPERTY_DATA: PropertyTabData = {
  overallScore: 724,

  extraDwellings: [
    {
      id: "ed_01",
      type: "Single lockup garage (separate)",
      sizeEstimate: "~28m² (single vehicle, with workbench)",
      construction: "Timber framed, corrugated iron roof, weatherboard cladding",
      condition: "Fair — roof shows surface rust consistent with age, cladding paint faded but intact",
      score: 6,
      estimatedReplacementCost: { low: 28_000, high: 45_000, notes: "New single garage, concrete floor, standard spec" },
      consentStatus: "unknown",
      photoReferences: [14, 15],
      aiSummary: "Photos 14 and 15 show a separate single-car lockup garage positioned at the rear of the section accessed via a concrete driveway. The structure appears to be timber-framed with corrugated iron roofing consistent with a 1970s–1980s build era, and weatherboard cladding that has lost most of its paint finish but does not show obvious structural damage. The iron roof displays the same surface rust pattern seen on the main dwelling's roof, suggesting both were last painted or treated around the same period. The garage represents genuine functional value to the property — secure off-street parking and storage that is increasingly uncommon in this suburb. At inspection, check the roof sheets for pinhole rust (which would indicate near-term replacement is needed), test the door mechanism, and confirm the structure is on the title. A LIM check is recommended to confirm consent status, as unconsented garages are common in properties of this age and can complicate insurance and sale.",
    },
  ],

  categories: [
    // ── 1. EXTERIOR ──────────────────────────────────────────────────────
    {
      id: "exterior",
      name: "Exterior",
      icon: "🏠",
      weight: 0.35,
      subItems: [
        {
          id: "ext_foundation",
          name: "Foundation",
          material: "Timber piles (inferred — not visible in photos)",
          estimatedAge: "~50 years (original to c.1975 build)",
          condition: "Unknown — not accessible from photos; TC2 land classification noted",
          score: null,
          urgencyLabel: "Not assessed — priority inspection item",
          confidenceTier: 3,
          evidenceSource: "Build era inference + Auckland Council TC2 classification",
          replacementCostWeight: 0.20,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [],
          estimatedReplacementCost: { low: 30_000, high: 150_000, notes: "Highly variable — depends on pile condition, number requiring replacement, and any seismic strengthening required" },
          aiSummary: "The foundation of this property is not visible in any of the 18 listing photos, which is typical — foundations are rarely photographed and inaccessible without subfloor entry. Based on the c.1975 build year, this property would most likely be constructed on reinforced concrete perimeter foundations or a concrete slab, both of which were common in Auckland residential construction through the 1970s. However, given Remuera's variable topography and sloping sites, a combination of perimeter foundations with interior timber or concrete piles is also possible. This property sits in a medium seismic hazard zone for Auckland, and while Remuera does not carry the TC2 liquefaction risk of Christchurch, the age of the foundation system warrants inspection regardless. We are not able to score this item from photos alone — it is rated Tier 3 and flagged as a priority inspection item. At inspection, request access to the subfloor cavity if one exists; look for pile condition, moisture, ground clearance, and any evidence of settlement or past repair. A pre-purchase building inspection by a registered inspector should specifically address the foundation system for a property of this age.",
        },
        {
          id: "ext_cladding",
          name: "Cladding",
          material: "Painted weatherboard — appears to be fibre cement board or solid timber (photo inconclusive)",
          estimatedAge: "~10–15 years since last repaint (estimated)",
          condition: "Fair — paint weathering evident on south-facing walls; no cracking or separation visible",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photos 1, 2, 16 — south wall visible; east and west walls not photographed",
          replacementCostWeight: 0.25,
          renovationLink: true,
          healthyHomesLink: false,
          photoReferences: [1, 2, 16],
          estimatedReplacementCost: { low: 18_000, high: 35_000, notes: "Full repaint including prep. Full reclad if substrate damage found — escalates to $40k–$120k" },
          aiSummary: "Photos 1, 2, and 16 show the front and partial rear elevations of the dwelling. The cladding appears to be horizontal weatherboard — the profile and shadow lines suggest either painted fibre cement (likely Hardiplank or equivalent) or solid timber weatherboard. The paint finish on the south-facing wall visible in photo 2 shows classic weathering: fading, some chalking, and minor paint flaking at the lower board edges near ground level. Critically, no cracking, separation at joints, or discolouration consistent with moisture ingress is visible in the photographed areas, which is reassuring for a property of this age. However, the east and west elevations are not shown in any listing photo, which means approximately 40% of the cladding exterior cannot be assessed with confidence — this earns a Tier 2 rating. At inspection, walk all four elevations and look specifically at: board-to-board joints (any gaps or lifting), window and door flashings (correct overlap and sealant condition), lower board edges near ground level (moisture absorption and rot), and any penetrations such as pipes or vents (flashing condition). The cladding is approaching the end of a typical 10–15 year repainting cycle; budgeting for a full exterior repaint in the next 1–3 years is advisable. See the Renovation tab for repaint cost estimate.",
        },
        {
          id: "ext_roof",
          name: "Roof",
          material: "Corrugated iron (steel) — original to build",
          estimatedAge: "~50 years (original, no evidence of replacement)",
          condition: "Below average — surface rust visible on ridgeline and valleys; paint system largely oxidised",
          score: 4,
          urgencyLabel: urgencyLabel(4),
          confidenceTier: 1,
          evidenceSource: "Photo 1 (aerial angle), Photo 16 (rear elevation showing ridgeline)",
          replacementCostWeight: 0.25,
          renovationLink: true,
          healthyHomesLink: false,
          photoReferences: [1, 16],
          estimatedReplacementCost: { low: 18_000, high: 32_000, notes: "Full re-roof in Colorsteel, standard pitch, 185m² floor area used as proxy for roof area (~210m² estimated). Includes gutter replacement." },
          aiSummary: "Photo 1 provides an elevated angle showing the front roof slope, and photo 16 captures the ridgeline from the rear. The roof is corrugated steel — almost certainly the original material from the c.1975 build — and shows consistent surface rust across the ridgeline and in the valleys where water pooling is most persistent. The paint system appears to be substantially oxidised, with the galvanised substrate now exposed across significant areas of the ridgeline flashing. For a 50-year-old iron roof in Auckland's coastal-influenced climate, this level of deterioration is not unexpected but does indicate the roof is in the latter portion of its functional life. Surface rust at this stage does not necessarily mean imminent failure — New Zealand iron roofs can often run another 5–10 years after visible rust appears if kept clear of debris and treated — but it does mean that replacement should be planned rather than deferred indefinitely. At inspection, have a roofer or building inspector physically walk the roof and check: sheet thickness (tap test for pin-holes), valley and ridgeline flashings (these fail first), gutters and downpipes (iron debris from a deteriorating roof blocks these rapidly), and the roof-to-wall junction flashings. We have included the cost of a full re-roof in the Renovation tab. Consider using this as a negotiation point — a roof replacement in the near term is a legitimate cost the vendor should factor into pricing.",
        },
        {
          id: "ext_windows",
          name: "Windows",
          material: "Mixed — aluminium DGU (living areas + master) and timber single-glazed (rear bedrooms)",
          estimatedAge: "Aluminium units: ~15–20 years. Timber units: original, ~50 years",
          condition: "Mixed — aluminium units fair/good; timber units poor (paint failure, early rot at sills)",
          score: 3,
          urgencyLabel: urgencyLabel(3),
          confidenceTier: 1,
          evidenceSource: "Photos 3, 7, 9 — rear bedroom windows clearly showing timber frames and rot",
          replacementCostWeight: 0.15,
          renovationLink: true,
          healthyHomesLink: true,
          photoReferences: [3, 7, 9],
          estimatedReplacementCost: { low: 2_400, high: 4_200, notes: "Replacement of 3 timber single-glazed units only — aluminium DGU units do not require replacement. 3 units × $800–$1,400 per unit supply and install." },
          aiSummary: "Photo 3 shows the main living area windows — aluminium-framed double-glazed units in fair condition consistent with a mid-2000s upgrade installation. These units show no significant deterioration and can reasonably be expected to serve another 10–15 years. Photos 7 and 9, however, show the rear bedroom windows, and these tell a different story: original timber-framed single-glazed windows that appear to be the same units installed when the house was built in the 1970s. The timber frames show classic age-related deterioration — paint failure exposing bare timber, and at the sill of the bedroom 2 window visible in photo 9, grain opening and discolouration consistent with early-stage moisture ingress. Single-glazed timber windows at this age present three compounding issues: ongoing moisture damage risk to surrounding framing if left untreated; meaningful heat loss and draught infiltration affecting Healthy Homes compliance; and an increasingly mismatched aesthetic with the upgraded living area windows. At inspection, press firmly on each timber sill — any softness or give indicates rot has progressed into the structural framing around the window opening, which significantly escalates the repair cost beyond the window unit itself. The three timber units in the rear bedrooms are the priority; replacement with aluminium double-glazed equivalents is included in the Renovation tab. The aluminium DGU units in the living areas do not require replacement.",
        },
        {
          id: "ext_soffits",
          name: "Soffits and Fascias",
          material: "Painted timber",
          estimatedAge: "Original to build (~50 years)",
          condition: "Fair — paint weathering consistent with age; no obvious bird entry or structural damage visible",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photo 1 (partial view of eave line)",
          replacementCostWeight: 0.08,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [1],
          estimatedReplacementCost: { low: 3_000, high: 10_000, notes: "Depends on extent of rot found at inspection. Repainting only: $1,500–$3,000" },
          aiSummary: "Photo 1 provides a partial view of the eave line on the front elevation. The timber soffits and fascias appear to be in fair condition for their age — paint is weathered but the boards do not show obvious cracking or sagging. Full assessment is not possible from the available photos as only one elevation is partially visible. For a 50-year-old property, soffits and fascias should be checked closely at inspection — they are a common entry point for birds and pests, and moisture-damaged soffits can indicate inadequate roof-to-wall junction drainage. At inspection, check for: any sagging or delamination of soffit boards, paint condition at joins and penetrations, any signs of bird or rodent entry, and the condition of gutter brackets which are often fixed to the fascia.",
        },
      ],
    },

    // ── 2. KITCHEN ───────────────────────────────────────────────────────
    {
      id: "kitchen",
      name: "Kitchen",
      icon: "🍳",
      weight: 0.10,
      subItems: [
        {
          id: "kit_cabinetry",
          name: "Cabinetry",
          material: "Painted MDF flat-panel — appears custom or semi-custom install",
          estimatedAge: "~5–8 years (estimated from style and condition)",
          condition: "Very good — clean, no visible damage, hardware consistent and functional",
          score: 8,
          urgencyLabel: urgencyLabel(8),
          confidenceTier: 1,
          evidenceSource: "Photos 4, 5",
          replacementCostWeight: 0.35,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [4, 5],
          estimatedReplacementCost: { low: 18_000, high: 40_000, notes: "Full kitchen cabinetry replacement — not required at this stage" },
          aiSummary: "Photos 4 and 5 show the kitchen in good natural light. The cabinetry is a modern flat-panel style with what appears to be a painted MDF or laminate finish in a light neutral tone, consistent with a renovation completed within the last 5–8 years. Cabinet doors are aligned with no visible warping or delamination, handles are consistent throughout, and the overall impression is of a well-executed renovation rather than a builder-grade install. No visible damage, staining, or evidence of moisture ingress near the sink or dishwasher positions. This is one of the property's genuine strengths and likely a significant driver of the listing presentation. No action required — monitor only.",
        },
        {
          id: "kit_benchtop",
          name: "Benchtop",
          material: "Stone composite (appears to be engineered quartz — Caesarstone or equivalent)",
          estimatedAge: "~5–8 years (matching cabinetry renovation)",
          condition: "Excellent — no chips, staining, or edge damage visible",
          score: 9,
          urgencyLabel: urgencyLabel(9),
          confidenceTier: 1,
          evidenceSource: "Photo 4",
          replacementCostWeight: 0.20,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [4],
          estimatedReplacementCost: { low: 3_500, high: 8_000, notes: "Engineered stone replacement — not required" },
          aiSummary: "Photo 4 shows the benchtop clearly. The surface appears to be an engineered quartz composite — the consistent grain pattern, edge profile, and surface reflectivity are consistent with a mid-to-high grade product such as Caesarstone or Silestone rather than natural stone or laminate. The surface shows no visible chips at the edges, no staining around the sink junction, and the overhanging section at the breakfast bar shows no cracking. Engineered stone benchtops of this quality have a practical lifespan of 20+ years with normal use. No action required.",
        },
        {
          id: "kit_appliances",
          name: "Appliances",
          material: "Mixed — induction hob (appears Smeg or equivalent), integrated rangehood, oven not visible",
          estimatedAge: "~5–8 years",
          condition: "Good — clean, no visible damage",
          score: 8,
          urgencyLabel: urgencyLabel(8),
          confidenceTier: 2,
          evidenceSource: "Photo 4 (hob and rangehood visible; oven not shown)",
          replacementCostWeight: 0.20,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [4],
          estimatedReplacementCost: { low: 3_000, high: 8_000, notes: "Full appliance replacement — not required. Individual appliance replacement depends on unit." },
          aiSummary: "Photo 4 shows a 4-zone induction hob that appears to be a European brand (the profile and control layout are consistent with Smeg, Bosch, or equivalent), paired with an integrated overhead rangehood. Both units appear clean and in good condition consistent with the wider kitchen renovation. The oven is not visible in any listing photo, which limits assessment. At inspection, test all appliances — hob zones, rangehood extraction and lighting, oven temperature accuracy, and any integrated dishwasher — and ask the vendor for any warranty documentation or service records.",
        },
        {
          id: "kit_sink",
          name: "Sink and Tapware",
          material: "Stainless steel undermount sink; matte black mixer tap",
          estimatedAge: "~5–8 years",
          condition: "Very good — no visible staining, lime scale, or damage",
          score: 8,
          urgencyLabel: urgencyLabel(8),
          confidenceTier: 1,
          evidenceSource: "Photo 5",
          replacementCostWeight: 0.10,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [5],
          estimatedReplacementCost: { low: 800, high: 2_500, notes: "Sink and tap replacement — not required" },
          aiSummary: "Photo 5 shows a single-bowl undermount stainless steel sink paired with a matte black mixer tap — a combination consistent with the wider kitchen renovation aesthetic. The sink surface shows no visible staining, pitting, or damage, and the tap finish appears intact without the flaking or corrosion that sometimes affects matte black coatings at the 5+ year mark. The undermount installation means the benchtop-to-sink junction is sealed and does not present a water ingress risk. No action required.",
        },
        {
          id: "kit_splashback",
          name: "Splashback",
          material: "Subway tile — white, glazed ceramic, approx 75×150mm",
          estimatedAge: "~5–8 years",
          condition: "Good — grout appears clean and intact with no cracking",
          score: 8,
          urgencyLabel: urgencyLabel(8),
          confidenceTier: 1,
          evidenceSource: "Photos 4, 5",
          replacementCostWeight: 0.08,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [4, 5],
          estimatedReplacementCost: { low: 800, high: 2_500, notes: "Splashback replacement — not required" },
          aiSummary: "Photos 4 and 5 show a classic subway tile splashback running from benchtop to underside of overhead cabinets. The grout appears clean and uniformly coloured with no evidence of cracking, staining, or hollow sections. Glazed ceramic subway tiles are a practical choice — highly durable, easy to clean, and resistant to the heat and moisture of a kitchen environment. No action required at this stage.",
        },
        {
          id: "kit_flooring",
          name: "Flooring",
          material: "Engineered timber or LVT (photo inconclusive — appears wood-look plank format)",
          estimatedAge: "~5–8 years",
          condition: "Good — no visible damage or wear",
          score: 8,
          urgencyLabel: urgencyLabel(8),
          confidenceTier: 2,
          evidenceSource: "Photo 4 (partial floor visible)",
          replacementCostWeight: 0.07,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [4],
          estimatedReplacementCost: { low: 2_500, high: 6_000, notes: "Kitchen floor area only — not required" },
          aiSummary: "Photo 4 shows a wood-look plank flooring in the kitchen area. The profile, width, and surface texture are consistent with either engineered timber or a quality LVT (luxury vinyl tile) product — the photo resolution does not allow a definitive determination. Both materials are appropriate for a kitchen environment and perform well in New Zealand conditions. No visible damage, lifting at edges, or discolouration is apparent. At inspection, check the join between the kitchen floor and the adjacent living area floor to confirm whether they are the same product and how the transition is handled.",
        },
      ],
    },

    // ── 3. BATHROOMS ─────────────────────────────────────────────────────
    {
      id: "bathrooms",
      name: "Bathroom(s)",
      icon: "🚿",
      weight: 0.08,
      subItems: [
        {
          id: "bath_shower",
          name: "Shower / Bath",
          material: "Tiled shower with frameless glass screen; separate freestanding bath (main bathroom)",
          estimatedAge: "~5–10 years (appears to be a past renovation)",
          condition: "Good — tiles and grout clean; screen intact; bath no visible chips",
          score: 7,
          urgencyLabel: urgencyLabel(7),
          confidenceTier: 1,
          evidenceSource: "Photo 6",
          replacementCostWeight: 0.30,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [6],
          estimatedReplacementCost: { low: 8_000, high: 18_000, notes: "Shower and bath replacement — not required at this stage" },
          aiSummary: "Photo 6 shows the main bathroom featuring a walk-in tiled shower with a frameless glass screen and what appears to be a freestanding bath positioned near the window. The tiling appears to be a large-format stone-look tile in a neutral palette, consistent with a bathroom renovation completed perhaps 5–10 years ago. The grout lines appear clean and uniformly coloured, and the frameless glass screen shows no permanent water marking or delamination of the seals. The freestanding bath has a classic profile and no visible chips or crazing. The overall presentation is above average for a property of this era. At inspection, specifically check the silicone seals at all floor-wall and wall-screen junctions — these are the primary moisture entry points — and press on the tiled wall at the shower to check for hollow sections or movement, which can indicate failed waterproofing membrane beneath.",
        },
        {
          id: "bath_waterproofing",
          name: "Waterproofing",
          material: "Cannot assess from photos — inferred from age and visible grout condition",
          estimatedAge: "~5–10 years (if replaced during renovation) or original (~50 years if not)",
          condition: "Probable — no water staining or efflorescence visible on adjacent surfaces",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photo 6 — no staining visible on adjacent walls or floor",
          replacementCostWeight: 0.25,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [6],
          estimatedReplacementCost: { low: 4_000, high: 12_000, notes: "Waterproofing remediation if required — highly variable depending on extent of damage" },
          aiSummary: "Waterproofing membranes are not directly visible in any listing photo, which is expected — they sit beneath the tile layer. Assessment must therefore be inferential. The positive indicators from photo 6 are: no water staining or mineral efflorescence on the external face of the shower wall or on the ceiling of any room below or adjacent to the bathroom; no visible cracking or movement in the tile installation; and grout condition that does not show the black mould patterns associated with persistent moisture behind the tile. These are encouraging signs but do not constitute confirmation. Given that the bathroom appears to have been renovated, if that renovation was completed to a proper standard it would have included a fresh waterproofing membrane — however, we cannot confirm this without documentation. At inspection, ask the vendor or agent for any records of the bathroom renovation, and specifically ask whether a licensed waterproofer was used and whether a membrane was installed. A building inspector with a moisture meter can detect elevated moisture readings in wall cavities behind the shower if waterproofing has failed.",
        },
        {
          id: "bath_vanity",
          name: "Vanity and Tapware",
          material: "Wall-hung vanity, white gloss finish; matte black tapware matching kitchen",
          estimatedAge: "~5–10 years",
          condition: "Good — no visible damage or corrosion",
          score: 8,
          urgencyLabel: urgencyLabel(8),
          confidenceTier: 1,
          evidenceSource: "Photo 6",
          replacementCostWeight: 0.20,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [6],
          estimatedReplacementCost: { low: 1_500, high: 4_500, notes: "Vanity and tap replacement — not required" },
          aiSummary: "Photo 6 shows a wall-hung vanity with a white gloss finish and integrated basin, paired with matte black tapware that coordinates with the kitchen — suggesting both areas were renovated as part of the same project. Wall-hung vanities are a practical choice as they simplify floor cleaning and the suspended installation makes underfloor moisture issues immediately obvious (no cabinet base to conceal water damage). No visible damage, staining, or corrosion on the tap finish. No action required.",
        },
        {
          id: "bath_ventilation",
          name: "Ventilation",
          material: "Exhaust fan (visible in photo 6); ducting to outside unconfirmed",
          estimatedAge: "Unknown — cannot determine from photos",
          condition: "Probable — fan present; ducting to outside not confirmable from photos",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photo 6 — exhaust fan visible in ceiling",
          replacementCostWeight: 0.08,
          renovationLink: false,
          healthyHomesLink: true,
          photoReferences: [6],
          estimatedReplacementCost: { low: 300, high: 1_200, notes: "Exhaust fan replacement and/or ducting correction to outside — Healthy Homes requirement" },
          aiSummary: "Photo 6 shows a ceiling-mounted exhaust fan in the bathroom. The presence of a fan is a positive indicator for Healthy Homes compliance, which requires bathroom extractor fans to be ducted to the outside of the building. However, whether this fan is ducted externally or simply recirculates air into the ceiling cavity cannot be confirmed from the photo. Recirculating fans — common in older NZ homes — do not meet the Healthy Homes standard and can contribute to moisture accumulation in ceiling insulation. At inspection, check for an external vent outlet visible on the soffit or exterior wall adjacent to the bathroom. If none is found, budget for a ducting correction — this is typically a straightforward and inexpensive fix but must be done before the property can be legally tenanted.",
        },
      ],
    },

    // ── 4. BEDROOMS ──────────────────────────────────────────────────────
    {
      id: "bedrooms",
      name: "Bedrooms",
      icon: "🛏️",
      weight: 0.07,
      subItems: [
        {
          id: "bed_master",
          name: "Master Bedroom",
          material: "Carpet (wool blend, appears mid-grade); built-in wardrobe with sliding doors",
          estimatedAge: "Carpet: ~8–12 years. Wardrobe: original build era",
          condition: "Good — carpet no visible staining or wear patterns; wardrobe functional",
          score: 7,
          urgencyLabel: urgencyLabel(7),
          confidenceTier: 1,
          evidenceSource: "Photo 8",
          replacementCostWeight: 0.40,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [8],
          estimatedReplacementCost: { low: 1_800, high: 4_000, notes: "Carpet replacement (master bedroom only) — not required at this stage" },
          aiSummary: "Photo 8 shows the master bedroom with wall-to-wall carpet in a neutral mid-tone, consistent with a mid-grade wool blend product. The carpet shows no visible wear tracks, staining, or lifting at the edges, suggesting it has been well-maintained and/or is relatively recent. The built-in wardrobe runs the full width of one wall with sliding panel doors — a practical and space-efficient configuration. The room appears to be a genuine queen or king-size double, with adequate natural light from the window visible in the background. No issues identified. At inspection, check beneath any furniture or mats for concealed staining, and test the wardrobe door mechanism.",
        },
        {
          id: "bed_bed2",
          name: "Bedroom 2",
          material: "Carpet; original timber single-glazed window (as noted in Windows assessment)",
          estimatedAge: "Carpet: estimated 10–15 years",
          condition: "Fair — carpet shows some wear; window poor condition as detailed separately",
          score: 5,
          urgencyLabel: urgencyLabel(5),
          confidenceTier: 2,
          evidenceSource: "Photo 9",
          replacementCostWeight: 0.35,
          renovationLink: true,
          healthyHomesLink: false,
          photoReferences: [9],
          estimatedReplacementCost: { low: 1_200, high: 3_000, notes: "Carpet replacement bedroom 2 — plan within 3–5 years" },
          aiSummary: "Photo 9 shows bedroom 2 — a standard double room. The carpet appears older than the master bedroom — a slightly different tone and some visible flattening of the pile consistent with 10–15 years of use. No significant staining is visible but the carpet is approaching the end of its functional aesthetic life. Importantly, this room contains one of the problematic timber single-glazed windows identified in the Exterior assessment; the window is a separate renovation item in the Renovation tab. At inspection, check for cold draught from the timber window and note any condensation staining on the adjacent wall — this would indicate the window unit has been allowing moisture into the wall framing.",
        },
        {
          id: "bed_bed3",
          name: "Bedroom 3",
          material: "Carpet; appears similar age to bedroom 2",
          estimatedAge: "Carpet: estimated 10–15 years",
          condition: "Fair",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photo 10 (partial)",
          replacementCostWeight: 0.25,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [10],
          estimatedReplacementCost: { low: 1_000, high: 2_500, notes: "Carpet replacement bedroom 3" },
          aiSummary: "Photo 10 provides a partial view of bedroom 3. The room appears to be a smaller double or large single. Carpet condition appears consistent with bedroom 2 — functional but approaching end of aesthetic life. No specific issues identified from the available photos. A full assessment requires physical inspection.",
        },
      ],
    },

    // ── 5. LIVING AREAS ──────────────────────────────────────────────────
    {
      id: "living",
      name: "Living Areas",
      icon: "🛋️",
      weight: 0.07,
      subItems: [
        {
          id: "liv_flooring",
          name: "Flooring",
          material: "Engineered timber or quality LVT — matching kitchen floor product",
          estimatedAge: "~5–8 years",
          condition: "Very good — no visible damage, consistent with kitchen renovation",
          score: 8,
          urgencyLabel: urgencyLabel(8),
          confidenceTier: 1,
          evidenceSource: "Photos 3, 11",
          replacementCostWeight: 0.25,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [3, 11],
          estimatedReplacementCost: { low: 6_000, high: 14_000, notes: "Living area floor replacement — not required" },
          aiSummary: "Photos 3 and 11 show the main living and dining areas. The flooring appears to be the same wood-look plank product as the kitchen — consistent tone and profile across both spaces, suggesting a whole-floor renovation rather than piecemeal replacement. The surface shows no visible damage, scratching, or lifting, and the plank installation appears professionally executed with consistent joint alignment. No action required.",
        },
        {
          id: "liv_heating",
          name: "Heating",
          material: "Heat pump — wall-mounted, visible in photo 3. Brand appears Mitsubishi Electric or Daikin.",
          estimatedAge: "~5–10 years (estimated from unit profile)",
          condition: "Good — clean, no visible damage",
          score: 8,
          urgencyLabel: urgencyLabel(8),
          confidenceTier: 1,
          evidenceSource: "Photo 3",
          replacementCostWeight: 0.30,
          renovationLink: false,
          healthyHomesLink: true,
          photoReferences: [3],
          estimatedReplacementCost: { low: 2_800, high: 5_500, notes: "Heat pump replacement — not required at this stage" },
          aiSummary: "Photo 3 clearly shows a wall-mounted heat pump unit in the main living area — the unit profile and louvre design are consistent with a mid-range Mitsubishi Electric or Daikin model. The unit appears clean and in good condition with no visible damage to the casing or louvres. A heat pump of this type, positioned in the main living area, satisfies the Healthy Homes heating requirement provided it is capable of maintaining 18°C in the room at 1°C outside — which units of this size class (typically 5–7kW) can generally achieve for a living room of the size visible in the photo. At inspection, test the unit in both heating and cooling modes, check that filters are clean, and ask the vendor when it was last serviced. No action required.",
        },
        {
          id: "liv_light",
          name: "Natural Light",
          material: "North-facing aspect with large windows — confirmed from listing orientation and photos",
          estimatedAge: "N/A",
          condition: "Excellent — strong natural light throughout main living areas",
          score: 9,
          urgencyLabel: urgencyLabel(9),
          confidenceTier: 1,
          evidenceSource: "Photos 3, 11 — shadow direction confirms north-facing",
          replacementCostWeight: 0.20,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [3, 11],
          estimatedReplacementCost: null,
          aiSummary: "The shadow direction and light quality visible in photos 3 and 11 are consistent with the listing's stated north-facing orientation. The main living and dining areas receive strong direct sunlight, which is one of the most valued attributes in New Zealand residential property and a genuine asset of this home. Large windows on the northern elevation maximise passive solar gain in winter while the roof overhang visible in photo 1 provides some summer shading. This characteristic contributes meaningfully to both liveability and Healthy Homes heating performance.",
        },
      ],
    },

    // ── 6. SERVICES ──────────────────────────────────────────────────────
    {
      id: "services",
      name: "Services",
      icon: "⚡",
      weight: 0.15,
      subItems: [
        {
          id: "svc_electrical",
          name: "Electrical Board",
          material: "Modern circuit breaker board — visible in photo 12",
          estimatedAge: "~15–20 years (estimated from board style)",
          condition: "Good — modern breakers present; no rewirable fuses visible",
          score: 7,
          urgencyLabel: urgencyLabel(7),
          confidenceTier: 1,
          evidenceSource: "Photo 12",
          replacementCostWeight: 0.40,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [12],
          estimatedReplacementCost: { low: 2_500, high: 6_000, notes: "Board upgrade if required — not immediately necessary from visible evidence" },
          aiSummary: "Photo 12 shows the electrical distribution board. The board contains modern circuit breakers (MCBs) rather than rewirable fuses, which is a meaningful positive for a 1975-built property — many homes of this era still have original rewirable fuse boards, which are a fire risk and an insurance concern. The presence of modern breakers suggests the electrical system has been partially or fully upgraded at some point. The board appears to have adequate circuit capacity for the property size, though the number of circuits is not fully legible in the photo. At inspection, have a licensed electrician check: RCD (residual current device) protection on wet area circuits — required by NZ standard; earthing continuity; and whether any aluminium wiring from the 1970s build remains in the walls (aluminium wiring is a fire risk that can be present in homes of this era). Ask the vendor for any electrical inspection certificates.",
        },
        {
          id: "svc_hotwater",
          name: "Hot Water Cylinder",
          material: "Electric cylinder — appears standard 180L or similar; brand and age label not visible",
          estimatedAge: "Unknown — label not visible in photos",
          condition: "Cannot fully assess — no rust staining or PRV discharge visible around unit",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photo 13 — cylinder visible in cupboard",
          replacementCostWeight: 0.20,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [13],
          estimatedReplacementCost: { low: 1_800, high: 4_500, notes: "Standard electric cylinder replacement. Heat pump hot water upgrade: $3,500–$6,000 including installation." },
          aiSummary: "Photo 13 shows a hot water cylinder installed in what appears to be a laundry or utility cupboard. The cylinder appears to be a standard electric storage unit — consistent with the typical installation for a property of this era. The age of the cylinder cannot be determined as the label is not visible in the photo, which is an important unknown: electric hot water cylinders typically have a 10–15 year service life, and a failed cylinder can cause significant water damage. At inspection, locate the manufacturer's label and record the installation date. Check around the base of the cylinder for rust staining or mineral deposits (indicating a past or slow leak), test the pressure relief valve, and confirm the element and thermostat are operational. If the cylinder is more than 15 years old, budget for replacement in the next 1–3 years regardless of apparent condition.",
        },
        {
          id: "svc_plumbing",
          name: "Plumbing (visible)",
          material: "Copper supply piping visible under kitchen sink; waste appears PVC",
          estimatedAge: "Supply: possible original copper (~50 years). Waste: appears more recent",
          condition: "Good (visible sections) — no corrosion, leaks, or mineral buildup visible",
          score: 7,
          urgencyLabel: urgencyLabel(7),
          confidenceTier: 2,
          evidenceSource: "Photo 5 (under-sink visible during open day photo)",
          replacementCostWeight: 0.30,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [5],
          estimatedReplacementCost: { low: 5_000, high: 25_000, notes: "Plumbing remediation — highly variable depending on pipe condition throughout" },
          aiSummary: "Photo 5 provides a partial view of the under-sink plumbing. The supply lines appear to be copper — consistent with 1970s construction, when copper was the standard material. Copper plumbing of this age can have a remaining service life of 20–40+ years depending on water quality and installation quality, and New Zealand's generally soft water is less corrosive than hard water systems. The visible sections show no obvious corrosion or mineral deposits. The waste pipe appears to be PVC, suggesting it has been replaced or updated at some point. Plumbing that is not visible (inside walls and under floors) cannot be assessed from listing photos. At inspection, check under all sinks and behind the washing machine connection for any evidence of slow leaks or water damage to cabinet bases and flooring.",
        },
      ],
    },

    // ── 7. GARAGE ────────────────────────────────────────────────────────
    {
      id: "garage",
      name: "Garage",
      icon: "🚗",
      weight: 0.08,
      subItems: [
        {
          id: "gar_main",
          name: "Garage (separate, single)",
          material: "Timber frame, corrugated iron roof, weatherboard cladding — matches main dwelling",
          estimatedAge: "~40–50 years (consistent with main dwelling era)",
          condition: "Fair — roof rust and faded cladding paint as noted; structure appears sound",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 1,
          evidenceSource: "Photos 14, 15",
          replacementCostWeight: 0.70,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [14, 15],
          estimatedReplacementCost: { low: 28_000, high: 45_000, notes: "See Extra Dwellings section — garage assessed there for value contribution" },
          aiSummary: "Photos 14 and 15 show the separate single-car garage at the rear of the property. The structure appears sound with no visible lean, sagging, or foundation movement. The surface rust on the corrugated iron roof and the faded weatherboard cladding are consistent with age-related deferred maintenance rather than structural deterioration. The garage door appears to be a manual tilt/swing type — no automatic opener visible. Internally, the garage appears to have a concrete floor and basic power (a light fitting is visible in photo 15). As a separate structure, the garage adds genuine value to the property — see the Extra Dwellings section for value contribution assessment. At inspection, confirm the door mechanism is functional, check for any roof leaks internally (water staining on internal rafters), and confirm the structure is on the title.",
        },
        {
          id: "gar_door",
          name: "Garage Door",
          material: "Manual tilt-panel door — appears steel or timber",
          estimatedAge: "Unknown — style consistent with older install",
          condition: "Functional — operates as expected from listing description",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photo 14",
          replacementCostWeight: 0.30,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [14],
          estimatedReplacementCost: { low: 1_200, high: 3_500, notes: "Manual tilt door replacement; auto-roller upgrade: $2,500–$4,500" },
          aiSummary: "Photo 14 shows the garage with what appears to be a manual tilt-panel door. The door appears functional and is in a closed position. No automatic opener is visible. At inspection, open and close the door to confirm the mechanism is smooth and the spring tension is correct — worn tilt-door springs can make the door difficult or dangerous to operate. If the property is being purchased as an investment, consider whether an automatic roller door upgrade would be a low-cost improvement that enhances rental appeal.",
        },
      ],
    },

    // ── 8. OUTDOOR & GROUNDS ─────────────────────────────────────────────
    {
      id: "outdoor",
      name: "Outdoor & Grounds",
      icon: "🌿",
      weight: 0.10,
      subItems: [
        {
          id: "out_deck",
          name: "Deck / Patio",
          material: "Timber deck — appears treated pine or hardwood, painted or oiled",
          estimatedAge: "~10–15 years (estimated from condition)",
          condition: "Fair — deck boards show weathering; no obvious structural issues visible",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photo 17",
          replacementCostWeight: 0.30,
          renovationLink: true,
          healthyHomesLink: false,
          photoReferences: [17],
          estimatedReplacementCost: { low: 4_000, high: 12_000, notes: "Deck board replacement (if substrate sound) or full rebuild. Size estimated ~25–30m² from photo." },
          aiSummary: "Photo 17 shows a timber deck off what appears to be the rear living area. The deck boards show weathering consistent with 10–15 years of exposure — silvering of the timber surface and some surface checking, suggesting the oil or paint finish has not been maintained on a regular cycle. The deck structure (joists and bearer system) is not visible in the photo and cannot be assessed. Surface-weathered deck boards are a cosmetic issue that can be addressed with sanding and re-oiling or painting for a relatively modest cost; however, structural deterioration of the framing below is a more serious concern that requires physical inspection. At inspection, check the deck framing from underneath — probe any timber in contact with or close to the ground, and look for joist hanger corrosion. Also check the deck-to-house connection flashing if the deck is attached to the main structure. If the deck is larger than 1.5m above ground, it should be consented and a LIM check is recommended to confirm. See the Renovation tab for a deck maintenance cost estimate.",
        },
        {
          id: "out_fencing",
          name: "Fencing",
          material: "Timber paling fence — partial boundary coverage visible",
          estimatedAge: "Mixed — sections appear different ages",
          condition: "Fair — some sections upright and maintained; rear boundary fence appears older",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photos 16, 17 (boundary fencing visible in background)",
          replacementCostWeight: 0.20,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [16, 17],
          estimatedReplacementCost: { low: 3_000, high: 9_000, notes: "Partial fence replacement — extent unknown without full site inspection" },
          aiSummary: "Photos 16 and 17 show partial views of the boundary fencing. The side boundary fence visible in photo 16 appears to be in reasonable condition — upright, with no obvious lean or significant board gaps. The rear boundary area visible in photo 17 shows an older fence section with some boards that appear weathered and potentially loose. Full boundary assessment is not possible from listing photos as coverage is incomplete. At inspection, walk all boundaries and check for: posts that are rotting at ground level (the most common failure point), significant lean, missing or loose boards that affect security, and whether the shared fences with neighbours are joint or sole responsibility — this affects both maintenance cost and what modifications can be made without consent.",
        },
        {
          id: "out_driveway",
          name: "Driveway",
          material: "Concrete — appears exposed aggregate or broom finish",
          estimatedAge: "~20–30 years (estimated)",
          condition: "Fair — some cracking visible but no significant heaving or drainage issues apparent",
          score: 6,
          urgencyLabel: urgencyLabel(6),
          confidenceTier: 2,
          evidenceSource: "Photo 14 (driveway visible leading to garage)",
          replacementCostWeight: 0.15,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [14],
          estimatedReplacementCost: { low: 6_000, high: 18_000, notes: "Full driveway replacement — not urgently required. Crack repair: $500–$2,000." },
          aiSummary: "Photo 14 shows the concrete driveway leading to the rear garage. The surface appears to be an older exposed aggregate or broom-finish concrete with some surface cracking visible — typical for concrete of this age in Auckland's variable climate. The cracks appear to be surface shrinkage cracks rather than structural movement (no significant offset or heaving visible), which is the less serious category. At inspection, check whether any cracks are wide enough to be a trip hazard or are admitting water under the slab; also check drainage — water pooling near the foundation is a concern.",
        },
        {
          id: "out_garden",
          name: "Garden",
          material: "Established planting — mix of native and exotic shrubs, lawn areas",
          estimatedAge: "Established — some planting appears 10–20+ years old",
          condition: "Good — well-maintained for listing; lawns appear healthy",
          score: 7,
          urgencyLabel: urgencyLabel(7),
          confidenceTier: 1,
          evidenceSource: "Photos 17, 18",
          replacementCostWeight: 0.15,
          renovationLink: false,
          healthyHomesLink: false,
          photoReferences: [17, 18],
          estimatedReplacementCost: null,
          aiSummary: "Photos 17 and 18 show the rear garden. The section appears to be a reasonable size for the Remuera suburb context, with established planting — mature shrubs and some specimen trees that would have taken 10–20+ years to reach their current size. The lawn areas appear well-maintained and healthy in the listing photos, though this is to be expected given the property is being presented for sale. The established mature planting is genuinely valuable — it provides privacy screening, shade, and aesthetic character that cannot be quickly replicated. At inspection, check for any trees that are close to the house foundation or drainage lines, as root intrusion is a long-term maintenance consideration.",
        },
      ],
    },
  ],
};
