import { NextRequest, NextResponse } from "next/server";

interface AgentLetterParams {
  propertyAddress: string;
  agentName?: string;
  agencyName?: string;
  userEmail: string;
  userName: string;
  reportId: string;
  uploadToken: string;
  gaps: Array<{
    area: string;
    label: string;
    description: string;
    inAgentLetter: boolean;
    inLimLetter: boolean;
  }>;
}

function buildAgentLetterHtml(p: AgentLetterParams): string {
  const photoGaps    = p.gaps.filter((g) => g.inAgentLetter && g.area.includes("photo") || g.area.includes("wall") || g.area.includes("board") || g.area.includes("floor") || g.area.includes("foundation"));
  const documentGaps = p.gaps.filter((g) => g.inLimLetter);
  const today = new Date().toLocaleDateString("en-NZ", { day: "numeric", month: "long", year: "numeric" });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<style>
  body { font-family: 'Georgia', serif; color: #1a1a1a; max-width: 720px; margin: 40px auto; padding: 0 40px; line-height: 1.6; font-size: 14px; }
  .logo { font-family: 'Arial', sans-serif; font-size: 22px; font-weight: 700; color: #00d4c8; letter-spacing: -0.02em; margin-bottom: 4px; }
  .tagline { font-size: 11px; color: #666; margin-bottom: 32px; }
  .divider { border: none; border-top: 2px solid #00d4c8; margin: 24px 0; }
  .section-title { font-family: 'Arial', sans-serif; font-weight: 700; font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; color: #666; margin: 24px 0 8px; }
  ol, ul { margin: 8px 0 16px 0; padding-left: 20px; }
  li { margin-bottom: 6px; }
  .footer { margin-top: 48px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
  .ref { font-family: 'Courier New', monospace; font-size: 11px; color: #666; }
  .upload-box { background: #f0fffe; border: 1px solid #9de6df; border-radius: 8px; padding: 12px 16px; margin: 16px 0; font-family: 'Arial', sans-serif; font-size: 12px; }
</style>
</head>
<body>
  <div class="logo">BDR Report</div>
  <div class="tagline">Know before you buy. · roiq.co.nz</div>

  <p>${today}</p>

  <p>
    ${p.agentName ? p.agentName + "<br />" : ""}
    ${p.agencyName ? p.agencyName + "<br />" : ""}
  </p>

  <p><strong>Re: Information Request — ${p.propertyAddress}</strong></p>

  <p>Dear ${p.agentName ? p.agentName.split(" ")[0] : "Agent"},</p>

  <p>
    We are conducting due diligence on the above-mentioned property on behalf of a prospective
    purchaser. To complete our property analysis, we require the following additional information
    and photographs.
  </p>

  ${p.gaps.filter((g) => g.inAgentLetter).length > 0 ? `
  <hr class="divider" />
  <div class="section-title">Photographs requested</div>
  <ol>
    ${p.gaps.filter((g) => g.inAgentLetter).map((g) => `
      <li><strong>${g.label}</strong> — ${g.description}</li>
    `).join("")}
  </ol>
  ` : ""}

  <hr class="divider" />
  <div class="section-title">Documents requested</div>
  <ol>
    <li>LIM report (if available — we will obtain independently if not)</li>
    <li>Building consent history for all structures on the property</li>
    ${p.propertyAddress.toLowerCase().includes("christchurch") || p.propertyAddress.toLowerCase().includes("canterbury") ? "<li>EQC claim history and repair records</li>" : ""}
    ${documentGaps.some((g) => g.area.includes("body_corporate")) ? "<li>Body corporate minutes (last 3 years)</li>" : ""}
    <li>Last roof inspection certificate (if available)</li>
  </ol>

  <hr class="divider" />
  <div class="section-title">Specific questions</div>
  <ol>
    <li>What is the confirmed gross floor area of the main dwelling?</li>
    <li>What year was the roof last replaced or professionally inspected?</li>
    <li>Are all structures on the property fully building-consented?</li>
    <li>What is the confirmed title type (freehold / cross-lease / unit title)?</li>
    <li>Has the electrical system been upgraded from the original installation?</li>
    <li>What is the age and capacity of the hot water cylinder?</li>
  </ol>

  <div class="upload-box">
    <strong>To send photos and documents directly:</strong><br />
    Upload portal (no login required): <strong>roiq.co.nz/upload/${p.uploadToken}</strong><br />
    Or email to: ${p.userEmail}<br />
    This link expires in 30 days.
  </div>

  <p>
    Please send your response at your earliest convenience. We appreciate your assistance
    in facilitating this due diligence process.
  </p>

  <p>
    Sincerely,<br />
    <strong>${p.userName}</strong><br />
    ${p.userEmail}
  </p>

  <div class="footer">
    Generated by BDR Report · roiq.co.nz · Reference: ${p.reportId}<br />
    This letter was generated using AI-assisted property analysis of publicly available listing data.
    BDR Report is not a registered property valuer, building inspector, or legal advisor.
  </div>
</body>
</html>`;
}

export async function POST(request: NextRequest) {
  let body: AgentLetterParams;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const html = buildAgentLetterHtml(body);

  return new NextResponse(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "X-Report-Id": body.reportId,
    },
  });
}
