// GENERATED by scripts/build-zoning-registry.mjs — do not edit by hand.
// Source: https://district-plans.nz/data/nz_district_plans.csv (district-plans.nz), retrieved 2026-08-23.
//
// Data ownership, licensing and currency remain with each council. 50 of
// 67 territorial authorities publish their zones as a queryable ArcGIS REST
// service; the remaining 17 offer only static maps, viewers or bulk
// downloads, and for those the report has to say plainly that it could not
// retrieve the zone rather than invent one or send the reader off to look.

export interface ZoningCouncil {
  /** Matches LINZ's `territorial_authority` on the address layer. */
  territory: string;
  service: string;
  /** Layer index within the service; null when the catalogue didn't name one. */
  layer: number | null;
  layerName: string;
  /** The council's own plan page, for a citation the reader can follow. */
  rulesUrl: string | null;
}

export const ZONING_COUNCILS: ZoningCouncil[] = [
  {
    "territory": "Ashburton District",
    "service": "https://gis.ecan.govt.nz/arcgis/rest/services/Ashburton_DC/ADC_DistrictPlan/MapServer",
    "layer": 19,
    "layerName": "Zone",
    "rulesUrl": "https://www.ashburtondc.govt.nz/home-and-property/planning-guidance-and-resource-consents/district-plan"
  },
  {
    "territory": "Auckland",
    "service": "https://services1.arcgis.com/n4yPwebTjJCmXB6W/arcgis/rest/services/Unitary_Plan_Base_Zone/FeatureServer",
    "layer": 0,
    "layerName": "Unitary Plan Base Zone",
    "rulesUrl": "https://www.aucklandcouncil.govt.nz/plans-projects-policies-reports-bylaws/our-plans-strategies/unitary-plan/Pages/default.aspx"
  },
  {
    "territory": "Buller District",
    "service": "https://utility.arcgis.com/usrsvcs/servers/ba01e90e08df446bbc16f0a6d900b722/rest/services/TTPP_Zones_and_Development_Areas/MapServer",
    "layer": null,
    "layerName": "Zones",
    "rulesUrl": "https://ttpp.nz/"
  },
  {
    "territory": "Carterton District",
    "service": "https://gis.mstn.govt.nz/arcgis/rest/services/ResourceManagementAndPlanning/Zones/MapServer",
    "layer": 0,
    "layerName": "Conservation Management",
    "rulesUrl": "https://www.wairarapaplan.co.nz/"
  },
  {
    "territory": "Central Hawke's Bay District",
    "service": "https://services8.arcgis.com/O26DwMB5KWy6K8pZ/ArcGIS/rest/services/District_Plan_Zones/FeatureServer",
    "layer": null,
    "layerName": "Zones",
    "rulesUrl": "https://www.chbdc.govt.nz/services/district-plan/"
  },
  {
    "territory": "Christchurch City",
    "service": "https://gis.ccc.govt.nz/server/rest/services/OpenData/DistrictPlan/FeatureServer",
    "layer": 78,
    "layerName": "DPZone",
    "rulesUrl": "https://districtplan.ccc.govt.nz/"
  },
  {
    "territory": "Clutha District",
    "service": "https://gis.cluthadc.govt.nz/arcgis/rest/services/DistrictPlan/MapServer",
    "layer": 27,
    "layerName": "Zoning",
    "rulesUrl": "https://www.cluthadc.govt.nz/property-rates-and-building/planning-and-resource-consents/district-plan-information"
  },
  {
    "territory": "Dunedin City",
    "service": "https://apps.dunedin.govt.nz/arcgis/rest/services/Public/SecondGenerationPlan_Zones/MapServer",
    "layer": 0,
    "layerName": "Residential",
    "rulesUrl": "https://www.dunedin.govt.nz/council/district-plan/2nd-generation-district-plan/read-the-plan"
  },
  {
    "territory": "Far North District",
    "service": "https://maps.fndc.govt.nz/server/rest/services/District_Plan_Zone_Maps/MapServer",
    "layer": 14,
    "layerName": "District Plan Zones",
    "rulesUrl": "https://www.fndc.govt.nz/Your-council/District-Plan/Operative-plan"
  },
  {
    "territory": "Gore District",
    "service": "https://services7.arcgis.com/308bMeGCJ1H5zqO0/arcgis/rest/services/Planning Zones/FeatureServer",
    "layer": null,
    "layerName": "Planning_Zones",
    "rulesUrl": "https://www.goredc.govt.nz/council/official-documents/district-plan"
  },
  {
    "territory": "Grey District",
    "service": "https://utility.arcgis.com/usrsvcs/servers/ba01e90e08df446bbc16f0a6d900b722/rest/services/TTPP_Zones_and_Development_Areas/MapServer",
    "layer": null,
    "layerName": "Zones",
    "rulesUrl": "https://ttpp.nz/"
  },
  {
    "territory": "Hamilton City",
    "service": "https://maps.hamilton.govt.nz/server/rest/services/agol_odp2017/DistrictPlan_Proposed_Decisions_2015_Zoning/MapServer",
    "layer": 32,
    "layerName": "Zoning",
    "rulesUrl": "https://hamilton.govt.nz/property-rates-and-building/district-plan/"
  },
  {
    "territory": "Hastings District",
    "service": "https://services1.arcgis.com/8L3DQUzjrkgEmDpQ/arcgis/rest/services/OpenData_OperativeDistrictPlan_Zones/FeatureServer",
    "layer": 39,
    "layerName": "Hastings DC Operative District Plan Zones",
    "rulesUrl": "https://www.hastingsdc.govt.nz/services/district-plan/"
  },
  {
    "territory": "Hurunui District",
    "service": "https://services1.arcgis.com/RNxkQaMWQcgbiF98/arcgis/rest/services/Canterbury_Operational_District_Plan_Zones_%28View%29/FeatureServer",
    "layer": 0,
    "layerName": "Canterbury Operational District Plan Zones",
    "rulesUrl": "https://www.hurunui.govt.nz/property-rates/district-plan"
  },
  {
    "territory": "Invercargill City",
    "service": "https://maps.icc.govt.nz/server/rest/services/LocalMaps/LocalMaps_DistrictPlan_Planning_2025/MapServer",
    "layer": 22,
    "layerName": "Planning Zones",
    "rulesUrl": "https://www.icc.govt.nz/council/policies-plans-bylaws/district-plan"
  },
  {
    "territory": "Kaikoura District",
    "service": "https://services1.arcgis.com/RNxkQaMWQcgbiF98/arcgis/rest/services/Canterbury_Operational_District_Plan_Zones_%28View%29/FeatureServer",
    "layer": 0,
    "layerName": "Canterbury Operational District Plan Zones",
    "rulesUrl": "https://www.kaikoura.govt.nz/council/plans-policies-reports/district-plan"
  },
  {
    "territory": "Kaipara District",
    "service": "https://services9.arcgis.com/DUYVFPAJ5YcaFDs0/arcgis/rest/services/District_Plan_Zones/FeatureServer",
    "layer": 20,
    "layerName": "Zones",
    "rulesUrl": "https://www.kaipara.govt.nz/services/district-plans"
  },
  {
    "territory": "Kapiti Coast District",
    "service": "https://maps.kapiticoast.govt.nz/server/rest/services/Public/District_Plan_Zones/FeatureServer",
    "layer": 0,
    "layerName": "Zones",
    "rulesUrl": "https://www.kapiticoast.govt.nz/council/forms-documents/district-plan/operative-district-plan-2021/"
  },
  {
    "territory": "Kawerau District",
    "service": "https://services6.arcgis.com/cPT953kF4vi3KAGL/arcgis/rest/services/KDC_District_Plan_Zones_2022/FeatureServer",
    "layer": null,
    "layerName": "KDC_DP_Zones_2022",
    "rulesUrl": "https://www.kaweraudc.govt.nz/files/documents/section_c_zones_rules_conditions_standards_and_terms.pdf"
  },
  {
    "territory": "Lower Hutt City",
    "service": "https://services1.arcgis.com/DlsnLEhGfXazS5Er/arcgis/rest/services/Lower_Hutt_District_Plan_Data/FeatureServer",
    "layer": null,
    "layerName": "ODPactivityareas",
    "rulesUrl": "https://www.huttcity.govt.nz/council/district-plan"
  },
  {
    "territory": "Mackenzie District",
    "service": "https://services1.arcgis.com/RNxkQaMWQcgbiF98/arcgis/rest/services/Canterbury_Operational_District_Plan_Zones_%28View%29/FeatureServer",
    "layer": 0,
    "layerName": "Canterbury Operational District Plan Zones",
    "rulesUrl": "https://www.mackenzie.govt.nz/council/strategies-plans-and-reports/district-plan"
  },
  {
    "territory": "Marlborough District",
    "service": "https://gis.marlborough.govt.nz/server/rest/services/DataPublic/ZonesMEPDecision/MapServer",
    "layer": 20,
    "layerName": "Zones",
    "rulesUrl": "https://www.marlborough.govt.nz/your-council/resource-management-policy-and-plans/proposed-marlborough-environment-plan-operative-in-part"
  },
  {
    "territory": "Masterton District",
    "service": "https://gis.mstn.govt.nz/arcgis/rest/services/ResourceManagementAndPlanning/Zones/MapServer",
    "layer": 0,
    "layerName": "Conservation Management",
    "rulesUrl": "https://www.wairarapaplan.co.nz/"
  },
  {
    "territory": "Napier City",
    "service": "https://spatial.napier.govt.nz/server/rest/services/NapierMaps/OperativeDistrictPlan_2025/MapServer",
    "layer": 10,
    "layerName": "District Plan Zones",
    "rulesUrl": "https://eplan.napier.govt.nz/eplan2025"
  },
  {
    "territory": "Nelson City",
    "service": "https://www.topofthesouthmaps.co.nz/arcgis/rest/services/DataPlanning/MapServer",
    "layer": null,
    "layerName": "Planning Zones > Planning Zone",
    "rulesUrl": "https://www.nelson.govt.nz/1your-council/resource-management-plans/eplan-view-the-interactive-resource-management-plans"
  },
  {
    "territory": "New Plymouth District",
    "service": "https://services2.arcgis.com/JthOmqz8HxPqljUO/arcgis/rest/services/OpenData_Strategy_DistrictPlan_PartOperative/FeatureServer",
    "layer": 51,
    "layerName": "NPDC_Strategy_DistrictPlan_PartOperative_Zone",
    "rulesUrl": "https://www.npdc.govt.nz/planning-our-future/district-plan/"
  },
  {
    "territory": "Ōpōtiki District",
    "service": "https://gis.boprc.govt.nz/server2/rest/services/BayOfPlentyMaps/PlansandRules/MapServer",
    "layer": 31,
    "layerName": "Opotiki District Plan Zones",
    "rulesUrl": "https://www.odc.govt.nz/our-council/plans-strategies/district-plan"
  },
  {
    "territory": "Porirua City",
    "service": "https://services1.arcgis.com/kIwRm3UCyRHYbM8a/arcgis/rest/services/Zones_PDP/FeatureServer",
    "layer": null,
    "layerName": "Zone",
    "rulesUrl": "https://poriruacity.govt.nz/your-council/city-planning-and-reporting/district-plan/district-plan-2025/"
  },
  {
    "territory": "Queenstown-Lakes District",
    "service": "https://gis.qldc.govt.nz/server/rest/services/DistrictPlan/Operative_District_Plan/FeatureServer",
    "layer": 37,
    "layerName": "Zones",
    "rulesUrl": "https://www.qldc.govt.nz/your-council/district-plan/"
  },
  {
    "territory": "Rangitikei District",
    "service": "https://services8.arcgis.com/rH83DoI7Xdq2nG28/ArcGIS/rest/services/EPLAN_zones_2024/FeatureServer",
    "layer": 48,
    "layerName": "EPLAN_zones_2024",
    "rulesUrl": "https://www.rangitikei.govt.nz/council/publications/district-plan"
  },
  {
    "territory": "Rotorua District",
    "service": "https://gis.rdc.govt.nz/server/rest/services/Core/Planning_and_Development/MapServer",
    "layer": 355,
    "layerName": "Zoning",
    "rulesUrl": "https://www.rotorualakescouncil.nz/property-building-bins/district-plan"
  },
  {
    "territory": "Selwyn District",
    "service": "https://gis.ecan.govt.nz/arcgis/rest/services/Selwyn_DC/SDC_DistrictPlan/MapServer",
    "layer": 25,
    "layerName": "Planning Zones",
    "rulesUrl": "https://www.selwyn.govt.nz/property-And-building/planning/selwyn-district-plan"
  },
  {
    "territory": "South Waikato District",
    "service": "https://services9.arcgis.com/pQ2VGNXWHZ4WkdmW/arcgis/rest/services/Plan_Zones/FeatureServer",
    "layer": 1,
    "layerName": "ActivityZonesSouthWaikato",
    "rulesUrl": "https://districtplan.southwaikato.govt.nz/"
  },
  {
    "territory": "South Wairarapa District",
    "service": "https://gis.mstn.govt.nz/arcgis/rest/services/ResourceManagementAndPlanning/Zones/MapServer",
    "layer": 0,
    "layerName": "Conservation Management",
    "rulesUrl": "https://www.wairarapaplan.co.nz/"
  },
  {
    "territory": "Southland District",
    "service": "https://services7.arcgis.com/XzQIGWOKjRuVk0Xy/arcgis/rest/services/EPLAN_DISTRICT_PLAN_LAYERS/FeatureServer",
    "layer": null,
    "layerName": "Zones",
    "rulesUrl": "https://www.southlanddc.govt.nz/home-and-property/resource-consents/district-plan/operative-district-plan-eplan/"
  },
  {
    "territory": "Tararua District",
    "service": "https://services-ap1.arcgis.com/ry1jWJjaLhqVCFK6/arcgis/rest/services/Planning_Zones_(Aggregated)/FeatureServer",
    "layer": 0,
    "layerName": "Planning_Zones_(Aggregated)",
    "rulesUrl": "https://www.tararuadc.govt.nz/publications/plans-and-reports/district-plan"
  },
  {
    "territory": "Tasman District",
    "service": "https://www.topofthesouthmaps.co.nz/arcgis/rest/services/DataPlanning/MapServer",
    "layer": null,
    "layerName": "Planning Zones > Planning Zone",
    "rulesUrl": "https://www.tasman.govt.nz/my-council/key-documents/tasman-resource-management-plan/volume-1-text/part-2-land"
  },
  {
    "territory": "Tauranga City",
    "service": "https://cemeteryaws.tauranga.govt.nz/server/rest/services/ePlan/ePlan_DistrictPlanBase/MapServer",
    "layer": 0,
    "layerName": "Planning Zones Operative",
    "rulesUrl": "https://www.tauranga.govt.nz/council/strategies-and-plans/tauranga-city-plan"
  },
  {
    "territory": "Thames-Coromandel District",
    "service": "https://services5.arcgis.com/MYtLmLEStmKgdmln/ArcGIS/rest/services/TCDC_Decisions_District_Plan/FeatureServer",
    "layer": 28,
    "layerName": "Zones",
    "rulesUrl": "https://www.tcdc.govt.nz/Our-Council/Plans-and-Reports/District-Plan/Thames-Coromandel-Operative-in-Part-District-Plan-2024"
  },
  {
    "territory": "Timaru District",
    "service": "https://services1.arcgis.com/RNxkQaMWQcgbiF98/arcgis/rest/services/Canterbury_Operational_District_Plan_Zones_%28View%29/FeatureServer",
    "layer": 0,
    "layerName": "Canterbury Operational District Plan Zones",
    "rulesUrl": "https://www.timaru.govt.nz/services/planning/district-plan"
  },
  {
    "territory": "Upper Hutt City",
    "service": "https://maps.upperhutt.govt.nz/arcgis/rest/services/District_Plan_Zones/MapServer",
    "layer": 0,
    "layerName": "District Plan Zones",
    "rulesUrl": "https://www.upperhutt.govt.nz/services/District-Plan"
  },
  {
    "territory": "Waikato District",
    "service": "https://services9.arcgis.com/hFOIM3RwvlDTA5Jf/arcgis/rest/services/District_Plan_Zones_Operative/FeatureServer",
    "layer": 0,
    "layerName": "District_Plan_Zones_Operative",
    "rulesUrl": "https://eplan.waikatodistrict.govt.nz/"
  },
  {
    "territory": "Waimakariri District",
    "service": "https://gisservices.waimakariri.govt.nz/arcgis/rest/services/District_Plan_2021/District_Plan_Zones_2021/MapServer",
    "layer": 10,
    "layerName": "Residential Zones - Variation 1",
    "rulesUrl": "https://www.waimakariri.govt.nz/council/district-development/district-plan"
  },
  {
    "territory": "Waimate District",
    "service": "https://services1.arcgis.com/RNxkQaMWQcgbiF98/arcgis/rest/services/Canterbury_Operational_District_Plan_Zones_(View)/FeatureServer",
    "layer": 0,
    "layerName": "Canterbury Operational District Plan Zones",
    "rulesUrl": "https://www.waimatedc.govt.nz/council/publications/district-plan"
  },
  {
    "territory": "Waitaki District",
    "service": "https://services1.arcgis.com/RNxkQaMWQcgbiF98/arcgis/rest/services/Canterbury_Operational_District_Plan_Zones_%28View%29/FeatureServer",
    "layer": 0,
    "layerName": "Canterbury Operational District Plan Zones",
    "rulesUrl": "https://www.waitaki.govt.nz/Services/Planning-and-Resource-Consents/District-plan/Current-District-Plan"
  },
  {
    "territory": "Wellington City",
    "service": "https://gis.wcc.govt.nz/arcgis/rest/services/2024DistrictPlan/2024DistrictPlan/MapServer",
    "layer": 122,
    "layerName": "Zones",
    "rulesUrl": "https://wellington.govt.nz/your-council/plans-policies-and-bylaws/district-plan/eplan"
  },
  {
    "territory": "Western Bay of Plenty District",
    "service": "https://map.westernbay.govt.nz/arcgisext/rest/services/District_Plan_WFS/MapServer",
    "layer": 66,
    "layerName": "Zone",
    "rulesUrl": "https://www.westernbay.govt.nz/property-rates-and-building/district-plan-and-resource-consents/district-plan/current-operative-district-plan"
  },
  {
    "territory": "Westland District",
    "service": "https://utility.arcgis.com/usrsvcs/servers/ba01e90e08df446bbc16f0a6d900b722/rest/services/TTPP_Zones_and_Development_Areas/MapServer",
    "layer": null,
    "layerName": "Zones",
    "rulesUrl": "https://ttpp.nz/"
  },
  {
    "territory": "Whakatane District",
    "service": "https://gis.whakatane.govt.nz/arcgis/rest/services/Planning/OperativeDistrictPlanNPS_ePlan/MapServer",
    "layer": 36,
    "layerName": "Planning Zones",
    "rulesUrl": "https://www.whakatane.govt.nz/documents/council-plans/operative-district-plan-2017"
  },
  {
    "territory": "Whangarei District",
    "service": "https://geo.wdc.govt.nz/server/rest/services/District_Plan_Public/MapServer",
    "layer": 14,
    "layerName": "Zones",
    "rulesUrl": "https://www.wdc.govt.nz/Services/Planning/District-Plan/ePlan"
  }
];
