import Navbar from "@/components/Navbar";
import Link from "next/link";
import { PRODUCT_NAME } from "@/lib/brand";

export const metadata = { title: `Terms of Service — ${PRODUCT_NAME}` };

const SECTIONS: { h: string; p: string[] }[] = [
  {
    h: `1. About ${PRODUCT_NAME}`,
    p: [
      `${PRODUCT_NAME} provides AI-assisted analysis of publicly available property-listing data and photos for New Zealand residential property. By using ${PRODUCT_NAME} you agree to these terms.`,
    ],
  },
  {
    h: "2. Not professional advice",
    p: [
      "${PRODUCT_NAME} reports are generated by automated analysis and are indicative only. They are not a registered property valuation, a building inspection report, legal advice, or financial advice.",
      "You must independently verify all material facts — including condition, title, hazards, consents, and financials — before making an offer or any financial decision. Always engage qualified professionals (a registered building inspector, valuer, lawyer, and where relevant a certified Healthy Homes assessor).",
    ],
  },
  {
    h: "3. Accuracy and limitations",
    p: [
      "Photo analysis is based on visible evidence only; conditions not visible in photos may differ materially. Financial projections are estimates based on historical data and your inputs, and past growth does not guarantee future performance.",
      `${PRODUCT_NAME} does not guarantee the accuracy, completeness, or timeliness of any report and is not liable for decisions made in reliance on a report.`,
    ],
  },
  {
    h: "4. Subscriptions and billing",
    p: [
      "Paid plans are billed monthly via our payment provider. You can cancel at any time; access continues until the end of the current billing period. Prices are in NZD and may change with notice.",
    ],
  },
  {
    h: "5. Acceptable use",
    p: [
      `You agree not to misuse the service, scrape or resell reports at scale, or use ${PRODUCT_NAME} to breach any third-party terms or applicable law.`,
    ],
  },
  {
    h: "6. Changes",
    p: [
      "We may update these terms from time to time. Continued use after an update constitutes acceptance of the revised terms.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bg)" }}>
      <Navbar />
      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold mb-1" style={{ color: "var(--text-primary)" }}>
          Terms of Service
        </h1>
        <p className="text-sm mb-8" style={{ color: "var(--text-muted)" }}>
          Last updated June 2026 · Draft for review
        </p>

        <div className="space-y-7">
          {SECTIONS.map((s) => (
            <section key={s.h}>
              <h2 className="font-semibold mb-2" style={{ color: "var(--text-primary)" }}>
                {s.h}
              </h2>
              {s.p.map((para, i) => (
                <p key={i} className="text-sm mb-2" style={{ color: "var(--text-secondary)", lineHeight: 1.7 }}>
                  {para}
                </p>
              ))}
            </section>
          ))}
        </div>

        <div className="mt-10 pt-6 text-sm" style={{ borderTop: "1px solid var(--border)", color: "var(--text-muted)" }}>
          Questions? See our <Link href="/privacy" style={{ color: "var(--brand)" }}>Privacy Policy</Link> or{" "}
          <Link href="/about" style={{ color: "var(--brand)" }}>About</Link> page.
        </div>
      </main>
    </div>
  );
}
